site_name: Python教程
theme: bootstrap4
site_dir: docs
site_url: https://docs.pilipili.top
docs_dir: md

nav:
  - Flask:
    - Watchlist: 'Watchlist.md'
    - The-Flask-Mega-Tutorial-zh: 'The-Flask-Mega-Tutorial-zh.md'
    - Flask-RESTFul-API: 'Flask-RESTFul-API.md'
    - Flask-socketio: 'Flask-SocketIO.md'
  - 网络编程:
    - socket: 'socket.md'
    - socketserver: 'socketserver.md'
    - websockets: 'websockets.md'
  - GUI:
    - PySide6: 'PySide6.md'
  - Python:
    - Threading: 'Threading.md'
    - Asyncio: 'Asycio.md'
