site_name: My Docs
theme: bootstrap4
site_dir: docs
docs_dir: md

nav:
  - Home: 'index.md'
  - Flask:
    - Watchlist: 'Watchlist.md'
    - Flask-WTForms: 'Flask-WTForms.md'
    - Flask之旅: 'Flask之旅.md'
    - The-Flask-Mega-Tutorial-zh: 'The-Flask-Mega-Tutorial-zh.md'
    - Flask-RESTFul-API: 'Flask-RESTFul-API.md'
    - Flask-socketio: 'Flask-SocketIO.md'
    - Flask学习资料: 'Flask学习资料.md'
  - 网络编程:
    - socket: 'socket.md'
    - socketserver: 'socketserver.md'
    - websockets: 'websockets.md'
  - GUI:
    - PySide入门: 'PySide入门.md'
    - PySide2教程: 'PySide2教程.md'
    - PySide6教程: 'PySide6教程.md'
    - Python-GUI学习资料: 'Python-GUI学习资料.md'
