site_name: My Docs
theme: bootstrap4
site_dir: docs
docs_dir: md

nav:
  - Home: 'index.md'
  - Flask:
    - Watchlist: 'Watchlist.md'
    - Flask-WTForms: 'Flask-WTForms.md'
    - Flask之旅: 'Flask之旅.md'
    - The-Flask-Mega-Tutorial-zh: 'The-Flask-Mega-Tutorial-zh.md'
    - Flask-RESTFul-API: 'Flask-RESTFul-API.md'
    - Flask-socketio: 'Flask-SocketIO.md'
    - Flask学习资料: 'Flask学习资料.md'
